[General]
# The interval in seconds at which the mod checks for addictions to recover from.
# Acts as both optimization and how quickly recovery can occur.
#
# Default: 15
iTickInterval = 60

# The minimum health the player must have to recover from addictions.
#
# Default: 0.7
fRecoveryMinHealth = 0.7

# The number of days since last activation until recovery chance improves.
# A value of 3 means that the player's chance of recovery starts *increasing* after 3 days 
# since last item activation and is severely *decreased* below 3 days.
# The more days have passed above this value, the higher the recovery chance.
#
# Default: 3
iRecoveryTimePivot = 3

# How much the player's endurance increases their base recovery chance.
#
# Default: 0.25
fRecoveryEnduranceFactor = 0.25

# How much the player's luck increases their base recovery chance.
#
# Default: 0.25
fRecoveryLuckFactor = 0.25


[Messages]
sRecoveryMessage0 = "With a lot of endurance, time, and a little bit of luck, you've managed to power through the shakes and jitters. You've recovered from %z addiction!"
sRecoveryMessage1 = "Kicking habits is always hard but you've managed to power through the worst of it. You've recovered from %z addiction!"
sRecoveryMessage2 = "A journey of a thousand miles begins with a single step -- and you've been walking for a while now. You've recovered from %z addiction!"
sRecoveryMessage3 = "They who conquer others are strong; they who conquer themselves are truly powerful. You've recovered from %z addiction!"
sRecoveryMessage4 = "Maintaining solid health has paid off and your body thanks you for it. You've recovered from %z addiction!"
sRecoveryMessage5 = "You feel cleansed after spending time sobering up in the blistering sun of the wasteland. You've recovered from %z addiction!"
sRecoveryMessage6 = "Fall seven times and stand up eight. Your abstinence has paid off, you've recovered from %z addiction!"